[colors.primary]
background = "#131416"
foreground = "#eeeeee"

[colors.normal]
black = "#000000"
red = "#f77172"
green = "#65a884"
yellow = "#cec999"
blue = "#74add2"
magenta = "#a980c4"
cyan = "#2d949f"
white = "#eeeeee"

[colors.bright]
black = "#89898a"
red = "#f77172"
green = "#65a884"
yellow = "#cec999"
blue = "#74add2"
magenta = "#a980c4"
cyan = "#2d949f"
white = "#eeeeee"
